// Auto-generated by BloppBOT - DO NOT EDIT MANUALLY
// Last updated: 2026-02-11

const INHOUSE_DATA = {
  "settings": {
    "mu": 25.0,
    "sigma": 8.333,
    "beta": 4.167,
    "tau": 0.0833,
    "drawProbability": 0.0
  },
  "players": {},
  "matches": [],
  "leagueUrl": null,
  "lastScraped": null
};

const PLAYER_NAMES = {
  "249844811": "blopp",
  "153867895": "Space Cowboy",
  "12853293": "Drea",
  "174635828": "Admiral rat",
  "400042038": "Ленске"
};
