// Auto-generated by BloppBOT - DO NOT EDIT MANUALLY
// Last updated: 2026-02-11

const INHOUSE_DATA = {
  "settings": {
    "mu": 25,
    "sigma": 8.333,
    "beta": 4.167,
    "tau": 0.0833,
    "drawProbability": 0
  },
  "players": {
    "174635828": {
      "name": "Admiral rat",
      "mu": 25,
      "sigma": 8.333,
      "games": 0,
      "wins": 0,
      "losses": 0,
      "lastPlayed": null
    }
  },
  "matches": [],
  "leagueUrl": null,
  "lastScraped": null
};

const PLAYER_NAMES = {
  "12853293": "Drea",
  "153867895": "Space Cowboy",
  "174635828": "Admiral rat",
  "249844811": "blopp",
  "400042038": "Ленске"
};
